on: [push]

env:
  node-version: 14.x

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: npm install -g @madlib-lang/madlib@0.13.0
      - run: madlib -v
      - run: madlib test
